### ISSUE TITLE
Java lang pointer error

### ISSUE THREAD

**Issue by chukwukai** [chukwukai/Automation-Sample-Project#1]
I am getting an java lang pointer error on line 15 on the getHotelMethods and on line 12 for the hotel java class. If you look at the error message, there are not looking for the actually map in the hotel class
<img width="997" alt="screen shot 2019-02-19 at 6 50 49 pm" src="https://user-images.githubusercontent.com/39497432/53163204-96570880-359b-11e9-9456-a35e0f44b7dd.png">

**Comment by rpetrina** [comment]
The map is not being built using a MapBuilder, which is a requirement for it to to return WebElement references properly.

**Comment by chukwukai** [comment]
This is working fine, thanks @rpetrina
