### ISSUE TITLE
Hotel Map's element is not performing as excepted

### ISSUE THREAD

**Issue by chukwukai** [chukwukai/Automation-Sample-Project#2]
So I am having an issue with the search hotel text on https://www.phptravels.net/

Anytime I am entering this field, the page will scroll down and not enter any field. It does select the text field
The line is 11 and 12 on the hotelMap.java. I used different ways to select the element
The line is 26 to send the actually text on the hotel.java

**Comment by rpetrina** [comment]
One thing I've tried in a situation like this before was to add another statement after you attempt to insert the text into the element (so after line 26 on) [Hotel.java](src/Test/Hotel.java). The statement I'd add would be something like wait.until(TextInElementEquals(_textyoutriedtoinsert_)); I don't remember the exact syntax but there are examples in the tests for the project we worked on together at Booz (leaving the name out here on purpose) give that a shot, it may be that the test is just not waiting long enough to type the text into the box before it moves on.

**Comment by chukwukai** [comment]
org.openqa.selenium.WebDriverException: unknown error: Element <input type="text" placeholder="Check in" value="" name="checkin" class="form input-lg dpd1" required=""> is not clickable at point (510, 328). Other element would receive the click: <div id="select2-drop-mask" class="select2-drop-mask" style=""></div>
  (Session info: chrome=72.0.3626.121)
This is what I got afterwards, i pushed my latests

**Comment by rpetrina** [comment]
Couple things I'd suggest doing in [Hotel.java](../tree/master/src/Test/Hotel.java):

1. Remove the `Keys.ENTER` from line 26
2. Add a `.click()` after waiting for visibility of the element returned from `hotelMap.getHotelName()` on line 25
3. Remove line 27

With those changes I can get the test run on my machine to click the text box and enter the `cityName` correctly - then you can work on selecting the `cityName` from the dropdown

**Comment by chukwukai** [comment]
This issue is now resolved
